// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: categoria.proto

package dispensa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Categoria struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome          string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	QuantidadeMax int64  `protobuf:"varint,3,opt,name=quantidadeMax,proto3" json:"quantidadeMax,omitempty"`
	QuantidadeMin int64  `protobuf:"varint,4,opt,name=quantidadeMin,proto3" json:"quantidadeMin,omitempty"`
}

func (x *Categoria) Reset() {
	*x = Categoria{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categoria_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Categoria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Categoria) ProtoMessage() {}

func (x *Categoria) ProtoReflect() protoreflect.Message {
	mi := &file_categoria_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Categoria.ProtoReflect.Descriptor instead.
func (*Categoria) Descriptor() ([]byte, []int) {
	return file_categoria_proto_rawDescGZIP(), []int{0}
}

func (x *Categoria) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Categoria) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Categoria) GetQuantidadeMax() int64 {
	if x != nil {
		return x.QuantidadeMax
	}
	return 0
}

func (x *Categoria) GetQuantidadeMin() int64 {
	if x != nil {
		return x.QuantidadeMin
	}
	return 0
}

type BuscarUmaCategoriaPeloId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BuscarUmaCategoriaPeloId) Reset() {
	*x = BuscarUmaCategoriaPeloId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categoria_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuscarUmaCategoriaPeloId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuscarUmaCategoriaPeloId) ProtoMessage() {}

func (x *BuscarUmaCategoriaPeloId) ProtoReflect() protoreflect.Message {
	mi := &file_categoria_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuscarUmaCategoriaPeloId.ProtoReflect.Descriptor instead.
func (*BuscarUmaCategoriaPeloId) Descriptor() ([]byte, []int) {
	return file_categoria_proto_rawDescGZIP(), []int{1}
}

func (x *BuscarUmaCategoriaPeloId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BuscarUmaCategoriaPeloNome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome string `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
}

func (x *BuscarUmaCategoriaPeloNome) Reset() {
	*x = BuscarUmaCategoriaPeloNome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categoria_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuscarUmaCategoriaPeloNome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuscarUmaCategoriaPeloNome) ProtoMessage() {}

func (x *BuscarUmaCategoriaPeloNome) ProtoReflect() protoreflect.Message {
	mi := &file_categoria_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuscarUmaCategoriaPeloNome.ProtoReflect.Descriptor instead.
func (*BuscarUmaCategoriaPeloNome) Descriptor() ([]byte, []int) {
	return file_categoria_proto_rawDescGZIP(), []int{2}
}

func (x *BuscarUmaCategoriaPeloNome) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

type BuscarUmaCategoriaPeloIdENome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
}

func (x *BuscarUmaCategoriaPeloIdENome) Reset() {
	*x = BuscarUmaCategoriaPeloIdENome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categoria_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuscarUmaCategoriaPeloIdENome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuscarUmaCategoriaPeloIdENome) ProtoMessage() {}

func (x *BuscarUmaCategoriaPeloIdENome) ProtoReflect() protoreflect.Message {
	mi := &file_categoria_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuscarUmaCategoriaPeloIdENome.ProtoReflect.Descriptor instead.
func (*BuscarUmaCategoriaPeloIdENome) Descriptor() ([]byte, []int) {
	return file_categoria_proto_rawDescGZIP(), []int{3}
}

func (x *BuscarUmaCategoriaPeloIdENome) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuscarUmaCategoriaPeloIdENome) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

type RetornoDeCategoriaSimples struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
}

func (x *RetornoDeCategoriaSimples) Reset() {
	*x = RetornoDeCategoriaSimples{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categoria_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetornoDeCategoriaSimples) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetornoDeCategoriaSimples) ProtoMessage() {}

func (x *RetornoDeCategoriaSimples) ProtoReflect() protoreflect.Message {
	mi := &file_categoria_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetornoDeCategoriaSimples.ProtoReflect.Descriptor instead.
func (*RetornoDeCategoriaSimples) Descriptor() ([]byte, []int) {
	return file_categoria_proto_rawDescGZIP(), []int{4}
}

func (x *RetornoDeCategoriaSimples) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RetornoDeCategoriaSimples) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

type RetornoDeCategoriaCompleto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome   string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	QtdMax int64  `protobuf:"varint,3,opt,name=qtd_max,json=qtdMax,proto3" json:"qtd_max,omitempty"`
	QtdMin int64  `protobuf:"varint,4,opt,name=qtd_min,json=qtdMin,proto3" json:"qtd_min,omitempty"`
}

func (x *RetornoDeCategoriaCompleto) Reset() {
	*x = RetornoDeCategoriaCompleto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categoria_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetornoDeCategoriaCompleto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetornoDeCategoriaCompleto) ProtoMessage() {}

func (x *RetornoDeCategoriaCompleto) ProtoReflect() protoreflect.Message {
	mi := &file_categoria_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetornoDeCategoriaCompleto.ProtoReflect.Descriptor instead.
func (*RetornoDeCategoriaCompleto) Descriptor() ([]byte, []int) {
	return file_categoria_proto_rawDescGZIP(), []int{5}
}

func (x *RetornoDeCategoriaCompleto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RetornoDeCategoriaCompleto) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *RetornoDeCategoriaCompleto) GetQtdMax() int64 {
	if x != nil {
		return x.QtdMax
	}
	return 0
}

func (x *RetornoDeCategoriaCompleto) GetQtdMin() int64 {
	if x != nil {
		return x.QtdMin
	}
	return 0
}

type CategoriaVazio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CategoriaVazio) Reset() {
	*x = CategoriaVazio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_categoria_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoriaVazio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoriaVazio) ProtoMessage() {}

func (x *CategoriaVazio) ProtoReflect() protoreflect.Message {
	mi := &file_categoria_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoriaVazio.ProtoReflect.Descriptor instead.
func (*CategoriaVazio) Descriptor() ([]byte, []int) {
	return file_categoria_proto_rawDescGZIP(), []int{6}
}

var File_categoria_proto protoreflect.FileDescriptor

var file_categoria_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x7b, 0x0a, 0x09, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x65,
	0x4d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x64, 0x61, 0x64, 0x65, 0x4d, 0x61, 0x78, 0x12, 0x24, 0x0a, 0x0d, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x64, 0x61, 0x64, 0x65, 0x4d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0d, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x65, 0x4d, 0x69, 0x6e, 0x22, 0x2a,
	0x0a, 0x18, 0x42, 0x75, 0x73, 0x63, 0x61, 0x72, 0x55, 0x6d, 0x61, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x61, 0x50, 0x65, 0x6c, 0x6f, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x1a, 0x42, 0x75,
	0x73, 0x63, 0x61, 0x72, 0x55, 0x6d, 0x61, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61,
	0x50, 0x65, 0x6c, 0x6f, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x1d,
	0x42, 0x75, 0x73, 0x63, 0x61, 0x72, 0x55, 0x6d, 0x61, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x61, 0x50, 0x65, 0x6c, 0x6f, 0x49, 0x64, 0x45, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d,
	0x65, 0x22, 0x3f, 0x0a, 0x19, 0x52, 0x65, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x44, 0x65, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f,
	0x6d, 0x65, 0x22, 0x72, 0x0a, 0x1a, 0x52, 0x65, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x44, 0x65, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x71, 0x74, 0x64, 0x5f, 0x6d, 0x61, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x71, 0x74, 0x64, 0x4d, 0x61, 0x78, 0x12, 0x17, 0x0a,
	0x07, 0x71, 0x74, 0x64, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x71, 0x74, 0x64, 0x4d, 0x69, 0x6e, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x61, 0x56, 0x61, 0x7a, 0x69, 0x6f, 0x32, 0xda, 0x02, 0x0a, 0x10, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a,
	0x15, 0x42, 0x75, 0x73, 0x63, 0x61, 0x44, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x61, 0x50, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x19, 0x2e, 0x42, 0x75, 0x73, 0x63, 0x61, 0x72, 0x55,
	0x6d, 0x61, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x50, 0x65, 0x6c, 0x6f, 0x49,
	0x64, 0x1a, 0x1b, 0x2e, 0x52, 0x65, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x44, 0x65, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x6f, 0x12, 0x53,
	0x0a, 0x17, 0x42, 0x75, 0x73, 0x63, 0x61, 0x44, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x61, 0x50, 0x6f, 0x72, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x1b, 0x2e, 0x42, 0x75, 0x73, 0x63,
	0x61, 0x72, 0x55, 0x6d, 0x61, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x50, 0x65,
	0x6c, 0x6f, 0x4e, 0x6f, 0x6d, 0x65, 0x1a, 0x1b, 0x2e, 0x52, 0x65, 0x74, 0x6f, 0x72, 0x6e, 0x6f,
	0x44, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x6f, 0x12, 0x30, 0x0a, 0x11, 0x43, 0x61, 0x64, 0x61, 0x73, 0x74, 0x72, 0x61, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x0a, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x61, 0x1a, 0x0f, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61,
	0x56, 0x61, 0x7a, 0x69, 0x6f, 0x12, 0x3e, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x61, 0x72,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x19, 0x2e, 0x42, 0x75, 0x73, 0x63,
	0x61, 0x72, 0x55, 0x6d, 0x61, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x50, 0x65,
	0x6c, 0x6f, 0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61,
	0x56, 0x61, 0x7a, 0x69, 0x6f, 0x12, 0x2e, 0x0a, 0x0f, 0x45, 0x64, 0x69, 0x74, 0x61, 0x72, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x0a, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x61, 0x1a, 0x0f, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61,
	0x56, 0x61, 0x7a, 0x69, 0x6f, 0x42, 0x18, 0x5a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x69,
	0x73, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x2f, 0x64, 0x69, 0x73, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_categoria_proto_rawDescOnce sync.Once
	file_categoria_proto_rawDescData = file_categoria_proto_rawDesc
)

func file_categoria_proto_rawDescGZIP() []byte {
	file_categoria_proto_rawDescOnce.Do(func() {
		file_categoria_proto_rawDescData = protoimpl.X.CompressGZIP(file_categoria_proto_rawDescData)
	})
	return file_categoria_proto_rawDescData
}

var file_categoria_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_categoria_proto_goTypes = []interface{}{
	(*Categoria)(nil),                     // 0: Categoria
	(*BuscarUmaCategoriaPeloId)(nil),      // 1: BuscarUmaCategoriaPeloId
	(*BuscarUmaCategoriaPeloNome)(nil),    // 2: BuscarUmaCategoriaPeloNome
	(*BuscarUmaCategoriaPeloIdENome)(nil), // 3: BuscarUmaCategoriaPeloIdENome
	(*RetornoDeCategoriaSimples)(nil),     // 4: RetornoDeCategoriaSimples
	(*RetornoDeCategoriaCompleto)(nil),    // 5: RetornoDeCategoriaCompleto
	(*CategoriaVazio)(nil),                // 6: CategoriaVazio
}
var file_categoria_proto_depIdxs = []int32{
	1, // 0: CategoriaService.BuscaDeCategoriaPorId:input_type -> BuscarUmaCategoriaPeloId
	2, // 1: CategoriaService.BuscaDeCategoriaPorNome:input_type -> BuscarUmaCategoriaPeloNome
	0, // 2: CategoriaService.CadastraCategoria:input_type -> Categoria
	1, // 3: CategoriaService.DeletarCategoria:input_type -> BuscarUmaCategoriaPeloId
	0, // 4: CategoriaService.EditarCategoria:input_type -> Categoria
	5, // 5: CategoriaService.BuscaDeCategoriaPorId:output_type -> RetornoDeCategoriaCompleto
	5, // 6: CategoriaService.BuscaDeCategoriaPorNome:output_type -> RetornoDeCategoriaCompleto
	6, // 7: CategoriaService.CadastraCategoria:output_type -> CategoriaVazio
	6, // 8: CategoriaService.DeletarCategoria:output_type -> CategoriaVazio
	6, // 9: CategoriaService.EditarCategoria:output_type -> CategoriaVazio
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_categoria_proto_init() }
func file_categoria_proto_init() {
	if File_categoria_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_categoria_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Categoria); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_categoria_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuscarUmaCategoriaPeloId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_categoria_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuscarUmaCategoriaPeloNome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_categoria_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuscarUmaCategoriaPeloIdENome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_categoria_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetornoDeCategoriaSimples); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_categoria_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetornoDeCategoriaCompleto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_categoria_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoriaVazio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_categoria_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_categoria_proto_goTypes,
		DependencyIndexes: file_categoria_proto_depIdxs,
		MessageInfos:      file_categoria_proto_msgTypes,
	}.Build()
	File_categoria_proto = out.File
	file_categoria_proto_rawDesc = nil
	file_categoria_proto_goTypes = nil
	file_categoria_proto_depIdxs = nil
}
