// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: produto.proto

package dispensa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Produto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome             string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	DataDeVencimento int64  `protobuf:"varint,3,opt,name=data_de_vencimento,json=dataDeVencimento,proto3" json:"data_de_vencimento,omitempty"`
	Categoria        int64  `protobuf:"varint,4,opt,name=categoria,proto3" json:"categoria,omitempty"`
}

func (x *Produto) Reset() {
	*x = Produto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_produto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Produto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Produto) ProtoMessage() {}

func (x *Produto) ProtoReflect() protoreflect.Message {
	mi := &file_produto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Produto.ProtoReflect.Descriptor instead.
func (*Produto) Descriptor() ([]byte, []int) {
	return file_produto_proto_rawDescGZIP(), []int{0}
}

func (x *Produto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Produto) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Produto) GetDataDeVencimento() int64 {
	if x != nil {
		return x.DataDeVencimento
	}
	return 0
}

func (x *Produto) GetCategoria() int64 {
	if x != nil {
		return x.Categoria
	}
	return 0
}

type BuscaDeProdutoPorId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BuscaDeProdutoPorId) Reset() {
	*x = BuscaDeProdutoPorId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_produto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuscaDeProdutoPorId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuscaDeProdutoPorId) ProtoMessage() {}

func (x *BuscaDeProdutoPorId) ProtoReflect() protoreflect.Message {
	mi := &file_produto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuscaDeProdutoPorId.ProtoReflect.Descriptor instead.
func (*BuscaDeProdutoPorId) Descriptor() ([]byte, []int) {
	return file_produto_proto_rawDescGZIP(), []int{1}
}

func (x *BuscaDeProdutoPorId) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BuscaDeProdutoPorNome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome string `protobuf:"bytes,1,opt,name=nome,proto3" json:"nome,omitempty"`
}

func (x *BuscaDeProdutoPorNome) Reset() {
	*x = BuscaDeProdutoPorNome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_produto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuscaDeProdutoPorNome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuscaDeProdutoPorNome) ProtoMessage() {}

func (x *BuscaDeProdutoPorNome) ProtoReflect() protoreflect.Message {
	mi := &file_produto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuscaDeProdutoPorNome.ProtoReflect.Descriptor instead.
func (*BuscaDeProdutoPorNome) Descriptor() ([]byte, []int) {
	return file_produto_proto_rawDescGZIP(), []int{2}
}

func (x *BuscaDeProdutoPorNome) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

type BuscaDeProdutosPorCategoria struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categoria int64 `protobuf:"varint,1,opt,name=categoria,proto3" json:"categoria,omitempty"`
}

func (x *BuscaDeProdutosPorCategoria) Reset() {
	*x = BuscaDeProdutosPorCategoria{}
	if protoimpl.UnsafeEnabled {
		mi := &file_produto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuscaDeProdutosPorCategoria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuscaDeProdutosPorCategoria) ProtoMessage() {}

func (x *BuscaDeProdutosPorCategoria) ProtoReflect() protoreflect.Message {
	mi := &file_produto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuscaDeProdutosPorCategoria.ProtoReflect.Descriptor instead.
func (*BuscaDeProdutosPorCategoria) Descriptor() ([]byte, []int) {
	return file_produto_proto_rawDescGZIP(), []int{3}
}

func (x *BuscaDeProdutosPorCategoria) GetCategoria() int64 {
	if x != nil {
		return x.Categoria
	}
	return 0
}

type RetornoDeProduto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome             string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	DataDeVencimento int64  `protobuf:"varint,3,opt,name=data_de_vencimento,json=dataDeVencimento,proto3" json:"data_de_vencimento,omitempty"`
	Categoria        int64  `protobuf:"varint,4,opt,name=categoria,proto3" json:"categoria,omitempty"`
}

func (x *RetornoDeProduto) Reset() {
	*x = RetornoDeProduto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_produto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetornoDeProduto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetornoDeProduto) ProtoMessage() {}

func (x *RetornoDeProduto) ProtoReflect() protoreflect.Message {
	mi := &file_produto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetornoDeProduto.ProtoReflect.Descriptor instead.
func (*RetornoDeProduto) Descriptor() ([]byte, []int) {
	return file_produto_proto_rawDescGZIP(), []int{4}
}

func (x *RetornoDeProduto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RetornoDeProduto) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *RetornoDeProduto) GetDataDeVencimento() int64 {
	if x != nil {
		return x.DataDeVencimento
	}
	return 0
}

func (x *RetornoDeProduto) GetCategoria() int64 {
	if x != nil {
		return x.Categoria
	}
	return 0
}

type ListaDeProdutos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lista []*RetornoDeProduto `protobuf:"bytes,1,rep,name=lista,proto3" json:"lista,omitempty"`
}

func (x *ListaDeProdutos) Reset() {
	*x = ListaDeProdutos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_produto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListaDeProdutos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaDeProdutos) ProtoMessage() {}

func (x *ListaDeProdutos) ProtoReflect() protoreflect.Message {
	mi := &file_produto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaDeProdutos.ProtoReflect.Descriptor instead.
func (*ListaDeProdutos) Descriptor() ([]byte, []int) {
	return file_produto_proto_rawDescGZIP(), []int{5}
}

func (x *ListaDeProdutos) GetLista() []*RetornoDeProduto {
	if x != nil {
		return x.Lista
	}
	return nil
}

type ProdutoVazio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProdutoVazio) Reset() {
	*x = ProdutoVazio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_produto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProdutoVazio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProdutoVazio) ProtoMessage() {}

func (x *ProdutoVazio) ProtoReflect() protoreflect.Message {
	mi := &file_produto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProdutoVazio.ProtoReflect.Descriptor instead.
func (*ProdutoVazio) Descriptor() ([]byte, []int) {
	return file_produto_proto_rawDescGZIP(), []int{6}
}

var File_produto_proto protoreflect.FileDescriptor

var file_produto_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x79, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x2c,
	0x0a, 0x12, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x64, 0x65, 0x5f, 0x76, 0x65, 0x6e, 0x63, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x64, 0x61, 0x74, 0x61,
	0x44, 0x65, 0x56, 0x65, 0x6e, 0x63, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x22, 0x25, 0x0a, 0x13, 0x42, 0x75,
	0x73, 0x63, 0x61, 0x44, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x50, 0x6f, 0x72, 0x49,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x2b, 0x0a, 0x15, 0x42, 0x75, 0x73, 0x63, 0x61, 0x44, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x74, 0x6f, 0x50, 0x6f, 0x72, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x22, 0x3b,
	0x0a, 0x1b, 0x42, 0x75, 0x73, 0x63, 0x61, 0x44, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f,
	0x73, 0x50, 0x6f, 0x72, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x22, 0x82, 0x01, 0x0a, 0x10,
	0x52, 0x65, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x44, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x64, 0x65, 0x5f,
	0x76, 0x65, 0x6e, 0x63, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x10, 0x64, 0x61, 0x74, 0x61, 0x44, 0x65, 0x56, 0x65, 0x6e, 0x63, 0x69, 0x6d, 0x65, 0x6e,
	0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x61,
	0x22, 0x3a, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x44, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x74, 0x6f, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x6c, 0x69, 0x73, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x65, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x44, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x74, 0x6f, 0x52, 0x05, 0x6c, 0x69, 0x73, 0x74, 0x61, 0x22, 0x0e, 0x0a, 0x0c,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x56, 0x61, 0x7a, 0x69, 0x6f, 0x32, 0xf1, 0x02, 0x0a,
	0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3e, 0x0a, 0x13, 0x42, 0x75, 0x73, 0x63, 0x61, 0x55, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74,
	0x6f, 0x50, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x14, 0x2e, 0x42, 0x75, 0x73, 0x63, 0x61, 0x44, 0x65,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x50, 0x6f, 0x72, 0x49, 0x64, 0x1a, 0x11, 0x2e, 0x52,
	0x65, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x44, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x12,
	0x42, 0x0a, 0x15, 0x42, 0x75, 0x73, 0x63, 0x61, 0x55, 0x6d, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x72,
	0x6f, 0x50, 0x6f, 0x72, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x16, 0x2e, 0x42, 0x75, 0x73, 0x63, 0x61,
	0x44, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x50, 0x6f, 0x72, 0x4e, 0x6f, 0x6d, 0x65,
	0x1a, 0x11, 0x2e, 0x52, 0x65, 0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x44, 0x65, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x74, 0x6f, 0x12, 0x51, 0x0a, 0x1f, 0x42, 0x75, 0x73, 0x63, 0x61, 0x54, 0x6f, 0x64, 0x6f,
	0x73, 0x4f, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x73, 0x44, 0x61, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x1c, 0x2e, 0x42, 0x75, 0x73, 0x63, 0x61, 0x44, 0x65,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x73, 0x50, 0x6f, 0x72, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x61, 0x1a, 0x10, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x44, 0x65, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x74, 0x6f, 0x73, 0x12, 0x27, 0x0a, 0x0c, 0x43, 0x72, 0x69, 0x61, 0x72, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x12, 0x08, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f,
	0x1a, 0x0d, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x56, 0x61, 0x7a, 0x69, 0x6f, 0x12,
	0x28, 0x0a, 0x0d, 0x45, 0x64, 0x69, 0x74, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f,
	0x12, 0x08, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x1a, 0x0d, 0x2e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x74, 0x6f, 0x56, 0x61, 0x7a, 0x69, 0x6f, 0x12, 0x35, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x12, 0x14, 0x2e, 0x42, 0x75,
	0x73, 0x63, 0x61, 0x44, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x50, 0x6f, 0x72, 0x49,
	0x64, 0x1a, 0x0d, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x56, 0x61, 0x7a, 0x69, 0x6f,
	0x42, 0x18, 0x5a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x69, 0x73, 0x70, 0x65, 0x6e, 0x73,
	0x61, 0x2f, 0x64, 0x69, 0x73, 0x70, 0x65, 0x6e, 0x73, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_produto_proto_rawDescOnce sync.Once
	file_produto_proto_rawDescData = file_produto_proto_rawDesc
)

func file_produto_proto_rawDescGZIP() []byte {
	file_produto_proto_rawDescOnce.Do(func() {
		file_produto_proto_rawDescData = protoimpl.X.CompressGZIP(file_produto_proto_rawDescData)
	})
	return file_produto_proto_rawDescData
}

var file_produto_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_produto_proto_goTypes = []interface{}{
	(*Produto)(nil),                     // 0: Produto
	(*BuscaDeProdutoPorId)(nil),         // 1: BuscaDeProdutoPorId
	(*BuscaDeProdutoPorNome)(nil),       // 2: BuscaDeProdutoPorNome
	(*BuscaDeProdutosPorCategoria)(nil), // 3: BuscaDeProdutosPorCategoria
	(*RetornoDeProduto)(nil),            // 4: RetornoDeProduto
	(*ListaDeProdutos)(nil),             // 5: ListaDeProdutos
	(*ProdutoVazio)(nil),                // 6: ProdutoVazio
}
var file_produto_proto_depIdxs = []int32{
	4, // 0: ListaDeProdutos.lista:type_name -> RetornoDeProduto
	1, // 1: ProdutoService.BuscaUmProdutoPorId:input_type -> BuscaDeProdutoPorId
	2, // 2: ProdutoService.BuscaUmProduroPorNome:input_type -> BuscaDeProdutoPorNome
	3, // 3: ProdutoService.BuscaTodosOsProdutosDaCategoria:input_type -> BuscaDeProdutosPorCategoria
	0, // 4: ProdutoService.CriarProduto:input_type -> Produto
	0, // 5: ProdutoService.EditarProduto:input_type -> Produto
	1, // 6: ProdutoService.DeletarProduto:input_type -> BuscaDeProdutoPorId
	4, // 7: ProdutoService.BuscaUmProdutoPorId:output_type -> RetornoDeProduto
	4, // 8: ProdutoService.BuscaUmProduroPorNome:output_type -> RetornoDeProduto
	5, // 9: ProdutoService.BuscaTodosOsProdutosDaCategoria:output_type -> ListaDeProdutos
	6, // 10: ProdutoService.CriarProduto:output_type -> ProdutoVazio
	6, // 11: ProdutoService.EditarProduto:output_type -> ProdutoVazio
	6, // 12: ProdutoService.DeletarProduto:output_type -> ProdutoVazio
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_produto_proto_init() }
func file_produto_proto_init() {
	if File_produto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_produto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Produto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_produto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuscaDeProdutoPorId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_produto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuscaDeProdutoPorNome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_produto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuscaDeProdutosPorCategoria); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_produto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetornoDeProduto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_produto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListaDeProdutos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_produto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProdutoVazio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_produto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_produto_proto_goTypes,
		DependencyIndexes: file_produto_proto_depIdxs,
		MessageInfos:      file_produto_proto_msgTypes,
	}.Build()
	File_produto_proto = out.File
	file_produto_proto_rawDesc = nil
	file_produto_proto_goTypes = nil
	file_produto_proto_depIdxs = nil
}
